apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name }}
    app.kubernetes.io/domain: {{ .Values.application.domain }}
    app.kubernetes.io/managed-by: {{ .Values.application.managedBy }}
    app.kubernetes.io/component: {{ .Values.application.component }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.application.name }}
